<?php
/*
 * This file is part of Aplus Framework Database Library.
 *
 * (c) Natan Felles <natanfelles@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace PHPSTORM_META;

registerArgumentsSet(
    'charsets',
    'armscii8',
    'ascii',
    'big5',
    'binary',
    'cp1250',
    'cp1251',
    'cp1256',
    'cp1257',
    'cp850',
    'cp852',
    'cp866',
    'cp932',
    'dec8',
    'eucjpms',
    'euckr',
    'gb2312',
    'gbk',
    'geostd8',
    'greek',
    'hebrew',
    'hp8',
    'keybcs2',
    'koi8r',
    'koi8u',
    'latin1',
    'latin2',
    'latin5',
    'latin7',
    'macce',
    'macroman',
    'sjis',
    'swe7',
    'tis620',
    'ucs2',
    'ujis',
    'utf16',
    'utf16le',
    'utf32',
    'utf8',
    'utf8mb3',
    'utf8mb4',
);
expectedArguments(
    \Framework\Database\Database::setCollations(),
    0,
    argumentsSet('charsets')
);
expectedArguments(
    \Framework\Database\Definition\AlterSchema::charset(),
    0,
    argumentsSet('charsets')
);
expectedArguments(
    \Framework\Database\Definition\CreateSchema::charset(),
    0,
    argumentsSet('charsets')
);
expectedArguments(
    \Framework\Database\Definition\Table\Columns\String\StringDataType::charset(),
    0,
    argumentsSet('charsets')
);
expectedArguments(
    \Framework\Database\Manipulation\LoadData::charset(),
    0,
    argumentsSet('charsets')
);
expectedArguments(
    \Framework\Database\Manipulation\Select::intoOutfile(),
    1,
    argumentsSet('charsets')
);
registerArgumentsSet(
    'manipulation_delete_opt',
    \Framework\Database\Manipulation\Delete::OPT_IGNORE,
    \Framework\Database\Manipulation\Delete::OPT_LOW_PRIORITY,
    \Framework\Database\Manipulation\Delete::OPT_QUICK,
);
expectedArguments(
    \Framework\Database\Manipulation\Delete::options(),
    0,
    argumentsSet('manipulation_delete_opt')
);
registerArgumentsSet(
    'manipulation_insert_opt',
    \Framework\Database\Manipulation\Insert::OPT_DELAYED,
    \Framework\Database\Manipulation\Insert::OPT_HIGH_PRIORITY,
    \Framework\Database\Manipulation\Insert::OPT_IGNORE,
    \Framework\Database\Manipulation\Insert::OPT_LOW_PRIORITY,
);
expectedArguments(
    \Framework\Database\Manipulation\Insert::options(),
    0,
    argumentsSet('manipulation_insert_opt')
);
registerArgumentsSet(
    'manipulation_load_data_opt',
    \Framework\Database\Manipulation\LoadData::OPT_CONCURRENT,
    \Framework\Database\Manipulation\LoadData::OPT_LOCAL,
    \Framework\Database\Manipulation\LoadData::OPT_LOW_PRIORITY,
);
expectedArguments(
    \Framework\Database\Manipulation\LoadData::options(),
    0,
    argumentsSet('manipulation_load_data_opt')
);
registerArgumentsSet(
    'manipulation_replace_opt',
    \Framework\Database\Manipulation\Replace::OPT_DELAYED,
    \Framework\Database\Manipulation\Replace::OPT_LOW_PRIORITY,
);
expectedArguments(
    \Framework\Database\Manipulation\Replace::options(),
    0,
    argumentsSet('manipulation_replace_opt')
);
registerArgumentsSet(
    'manipulation_select_opt',
    \Framework\Database\Manipulation\Select::OPT_ALL,
    \Framework\Database\Manipulation\Select::OPT_DISTINCT,
    \Framework\Database\Manipulation\Select::OPT_DISTINCTROW,
    \Framework\Database\Manipulation\Select::OPT_HIGH_PRIORITY,
    \Framework\Database\Manipulation\Select::OPT_SQL_BIG_RESULT,
    \Framework\Database\Manipulation\Select::OPT_SQL_BUFFER_RESULT,
    \Framework\Database\Manipulation\Select::OPT_SQL_CACHE,
    \Framework\Database\Manipulation\Select::OPT_SQL_CALC_FOUND_ROWS,
    \Framework\Database\Manipulation\Select::OPT_SQL_NO_CACHE,
    \Framework\Database\Manipulation\Select::OPT_SQL_SMALL_RESULT,
    \Framework\Database\Manipulation\Select::OPT_STRAIGHT_JOIN,
);
expectedArguments(
    \Framework\Database\Manipulation\Select::options(),
    0,
    argumentsSet('manipulation_select_opt')
);
registerArgumentsSet(
    'manipulation_update_opt',
    \Framework\Database\Manipulation\Update::OPT_IGNORE,
    \Framework\Database\Manipulation\Update::OPT_LOW_PRIORITY,
);
expectedArguments(
    \Framework\Database\Manipulation\Update::options(),
    0,
    argumentsSet('manipulation_update_opt')
);
registerArgumentsSet(
    'manipulation_with_opt',
    \Framework\Database\Manipulation\With::OPT_RECURSIVE
);
expectedArguments(
    \Framework\Database\Manipulation\With::options(),
    0,
    argumentsSet('manipulation_with_opt')
);
registerArgumentsSet(
    'foreign_key_opt',
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::OPT_CASCADE,
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::OPT_NO_ACTION,
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::OPT_RESTRICT,
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::OPT_SET_NULL,
);
expectedArguments(
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::onDelete(),
    0,
    argumentsSet('foreign_key_opt')
);
expectedArguments(
    \Framework\Database\Definition\Table\Indexes\Keys\ForeignKey::onUpdate(),
    0,
    argumentsSet('foreign_key_opt')
);
